// ─── Collection types ─────────────────────────────────────────────────────────

export type CollectionType =
  | 'franchise' | 'studio' | 'director' | 'actor'
  | 'genre' | 'tv' | 'decade' | 'mood' | 'awards'
  | 'theme' | 'classics';

export interface CollectionRules {
  /** TMDB keyword names — resolved to IDs at fetch time, OR-ed together */
  keywords?: string[];
  /** TMDB company name — resolved to ID at fetch time */
  studio?: string;
  /** Director name — resolved via person search + crew credits */
  director?: string;
  /** Actor name — resolved via person search + with_cast */
  actor?: string;
  /** Single genre name (movie) — mapped to TMDB genre ID */
  genre?: string;
  /** Multiple genre names (movie) — OR-ed together */
  genres?: string[];
  /** Force TV-only results */
  media_type?: 'movie' | 'tv';
  /** Pre-resolved TMDB network ID (e.g. HBO=49, Netflix=213) */
  network_id?: number;
  /** Pre-resolved TMDB TV genre ID */
  tv_genre_id?: number;
  /** TMDB TV show type: 0=Documentary, 1=News, 2=Miniseries, 3=Reality, 4=Scripted, 5=Talk, 6=Video */
  with_type?: number;
  /** Year range start (inclusive) */
  release_date_gte?: number;
  /** Year range end (inclusive) */
  release_date_lte?: number;
  /** Minimum vote average */
  rating_gte?: number;
}

export interface Collection {
  title: string;
  slug: string;
  type: CollectionType;
  description: string;
  rules: CollectionRules;
  sort: 'rating' | 'release_date' | 'popularity';
  limit: number;
}

// ─── Collection data ──────────────────────────────────────────────────────────

export const COLLECTIONS: Collection[] = [
  // ── Franchises ───────────────────────────────────────────────────────────────
  {
    title: 'Marvel Cinematic Universe',
    slug: 'marvel-cinematic-universe',
    type: 'franchise',
    description: 'Movies and series that are part of the Marvel Cinematic Universe.',
    rules: { keywords: ['marvel cinematic universe', 'marvel studios'] },
    sort: 'release_date',
    limit: 60,
  },
  {
    title: 'Star Wars Universe',
    slug: 'star-wars-universe',
    type: 'franchise',
    description: 'Movies and shows set in the Star Wars universe.',
    rules: { keywords: ['star wars'] },
    sort: 'release_date',
    limit: 40,
  },
  {
    title: 'DC Universe Movies',
    slug: 'dc-universe-movies',
    type: 'franchise',
    description: 'Movies based on DC Comics characters.',
    rules: { keywords: ['dc comics', 'dc universe'] },
    sort: 'release_date',
    limit: 60,
  },
  {
    title: 'Wizarding World',
    slug: 'wizarding-world',
    type: 'franchise',
    description: 'Harry Potter and Fantastic Beasts movies.',
    rules: { keywords: ['harry potter', 'wizarding world'] },
    sort: 'release_date',
    limit: 20,
  },
  {
    title: 'Alien & Predator Universe',
    slug: 'alien-predator-universe',
    type: 'franchise',
    description: 'Movies set in the Alien and Predator universes.',
    rules: { keywords: ['alien', 'predator', 'xenomorph'] },
    sort: 'release_date',
    limit: 20,
  },
  {
    title: 'The Lord of the Rings Saga',
    slug: 'the-lord-of-the-rings-saga',
    type: 'franchise',
    description: 'Middle‑earth movies.',
    rules: { keywords: ['middle earth', 'lord of the rings'] },
    sort: 'release_date',
    limit: 10,
  },
  {
    title: 'James Bond Movies',
    slug: 'james-bond-movies',
    type: 'franchise',
    description: 'All official James Bond movies.',
    rules: { keywords: ['james bond'] },
    sort: 'release_date',
    limit: 30,
  },
  {
    title: 'Mission Impossible Movies',
    slug: 'mission-impossible-movies',
    type: 'franchise',
    description: 'Spy action franchise starring Tom Cruise.',
    rules: { keywords: ['mission impossible'] },
    sort: 'release_date',
    limit: 10,
  },
  {
    title: 'Fast & Furious Saga',
    slug: 'fast-furious-saga',
    type: 'franchise',
    description: 'Street racing action franchise.',
    rules: { keywords: ['fast and furious'] },
    sort: 'release_date',
    limit: 15,
  },
  {
    title: 'Jurassic Park Franchise',
    slug: 'jurassic-park-franchise',
    type: 'franchise',
    description: 'Dinosaur adventure franchise.',
    rules: { keywords: ['jurassic park', 'jurassic world'] },
    sort: 'release_date',
    limit: 10,
  },

  // ── Studios ───────────────────────────────────────────────────────────────────
  {
    title: 'Pixar Animation Studios Movies',
    slug: 'pixar-animation-studios-movies',
    type: 'studio',
    description: 'Movies produced by Pixar Animation Studios.',
    rules: { studio: 'Pixar Animation Studios' },
    sort: 'rating',
    limit: 60,
  },
  {
    title: 'Studio Ghibli Movies',
    slug: 'studio-ghibli-movies',
    type: 'studio',
    description: 'Movies produced by Studio Ghibli.',
    rules: { studio: 'Studio Ghibli' },
    sort: 'rating',
    limit: 60,
  },
  {
    title: 'A24 Movies',
    slug: 'a24-movies',
    type: 'studio',
    description: 'Movies produced by A24.',
    rules: { studio: 'A24' },
    sort: 'rating',
    limit: 60,
  },
  {
    title: 'DreamWorks Animation Movies',
    slug: 'dreamworks-animation-movies',
    type: 'studio',
    description: 'Movies produced by DreamWorks Animation.',
    rules: { studio: 'DreamWorks Animation' },
    sort: 'rating',
    limit: 60,
  },
  {
    title: 'Walt Disney Animation Studios Movies',
    slug: 'walt-disney-animation-studios-movies',
    type: 'studio',
    description: 'Movies produced by Walt Disney Animation Studios.',
    rules: { studio: 'Walt Disney Animation Studios' },
    sort: 'rating',
    limit: 60,
  },
  {
    title: 'Laika Movies',
    slug: 'laika-movies',
    type: 'studio',
    description: 'Movies produced by Laika.',
    rules: { studio: 'Laika' },
    sort: 'rating',
    limit: 60,
  },
  {
    title: 'Illumination Movies',
    slug: 'illumination-movies',
    type: 'studio',
    description: 'Movies produced by Illumination.',
    rules: { studio: 'Illumination' },
    sort: 'rating',
    limit: 60,
  },
  {
    title: 'Warner Bros Movies',
    slug: 'warner-bros-movies',
    type: 'studio',
    description: 'Movies produced by Warner Bros.',
    rules: { studio: 'Warner Bros. Pictures' },
    sort: 'rating',
    limit: 60,
  },
  {
    title: 'Legendary Pictures Movies',
    slug: 'legendary-pictures-movies',
    type: 'studio',
    description: 'Movies produced by Legendary Pictures.',
    rules: { studio: 'Legendary Pictures' },
    sort: 'rating',
    limit: 60,
  },
  {
    title: 'Blumhouse Productions Movies',
    slug: 'blumhouse-productions-movies',
    type: 'studio',
    description: 'Movies produced by Blumhouse Productions.',
    rules: { studio: 'Blumhouse Productions' },
    sort: 'rating',
    limit: 60,
  },

  // ── Directors ─────────────────────────────────────────────────────────────────
  {
    title: 'Movies by Christopher Nolan',
    slug: 'movies-by-christopher-nolan',
    type: 'director',
    description: 'Films directed by Christopher Nolan.',
    rules: { director: 'Christopher Nolan' },
    sort: 'rating',
    limit: 30,
  },
  {
    title: 'Movies by Quentin Tarantino',
    slug: 'movies-by-quentin-tarantino',
    type: 'director',
    description: 'Films directed by Quentin Tarantino.',
    rules: { director: 'Quentin Tarantino' },
    sort: 'rating',
    limit: 30,
  },
  {
    title: 'Movies by Steven Spielberg',
    slug: 'movies-by-steven-spielberg',
    type: 'director',
    description: 'Films directed by Steven Spielberg.',
    rules: { director: 'Steven Spielberg' },
    sort: 'rating',
    limit: 30,
  },
  {
    title: 'Movies by Martin Scorsese',
    slug: 'movies-by-martin-scorsese',
    type: 'director',
    description: 'Films directed by Martin Scorsese.',
    rules: { director: 'Martin Scorsese' },
    sort: 'rating',
    limit: 30,
  },
  {
    title: 'Movies by Denis Villeneuve',
    slug: 'movies-by-denis-villeneuve',
    type: 'director',
    description: 'Films directed by Denis Villeneuve.',
    rules: { director: 'Denis Villeneuve' },
    sort: 'rating',
    limit: 30,
  },
  {
    title: 'Movies by Ridley Scott',
    slug: 'movies-by-ridley-scott',
    type: 'director',
    description: 'Films directed by Ridley Scott.',
    rules: { director: 'Ridley Scott' },
    sort: 'rating',
    limit: 30,
  },
  {
    title: 'Movies by Wes Anderson',
    slug: 'movies-by-wes-anderson',
    type: 'director',
    description: 'Films directed by Wes Anderson.',
    rules: { director: 'Wes Anderson' },
    sort: 'rating',
    limit: 30,
  },
  {
    title: 'Movies by David Fincher',
    slug: 'movies-by-david-fincher',
    type: 'director',
    description: 'Films directed by David Fincher.',
    rules: { director: 'David Fincher' },
    sort: 'rating',
    limit: 30,
  },
  {
    title: 'Movies by Greta Gerwig',
    slug: 'movies-by-greta-gerwig',
    type: 'director',
    description: 'Films directed by Greta Gerwig.',
    rules: { director: 'Greta Gerwig' },
    sort: 'rating',
    limit: 30,
  },
  {
    title: 'Movies by Hayao Miyazaki',
    slug: 'movies-by-hayao-miyazaki',
    type: 'director',
    description: 'Films directed by Hayao Miyazaki.',
    rules: { director: 'Hayao Miyazaki' },
    sort: 'rating',
    limit: 30,
  },

  // ── Actors ────────────────────────────────────────────────────────────────────
  {
    title: 'Movies with Leonardo DiCaprio',
    slug: 'movies-with-leonardo-dicaprio',
    type: 'actor',
    description: 'Movies starring Leonardo DiCaprio.',
    rules: { actor: 'Leonardo DiCaprio' },
    sort: 'rating',
    limit: 40,
  },
  {
    title: 'Movies with Tom Hanks',
    slug: 'movies-with-tom-hanks',
    type: 'actor',
    description: 'Movies starring Tom Hanks.',
    rules: { actor: 'Tom Hanks' },
    sort: 'rating',
    limit: 40,
  },
  {
    title: 'Movies with Robert De Niro',
    slug: 'movies-with-robert-de-niro',
    type: 'actor',
    description: 'Movies starring Robert De Niro.',
    rules: { actor: 'Robert De Niro' },
    sort: 'rating',
    limit: 40,
  },
  {
    title: 'Movies with Scarlett Johansson',
    slug: 'movies-with-scarlett-johansson',
    type: 'actor',
    description: 'Movies starring Scarlett Johansson.',
    rules: { actor: 'Scarlett Johansson' },
    sort: 'rating',
    limit: 40,
  },
  {
    title: 'Movies with Brad Pitt',
    slug: 'movies-with-brad-pitt',
    type: 'actor',
    description: 'Movies starring Brad Pitt.',
    rules: { actor: 'Brad Pitt' },
    sort: 'rating',
    limit: 40,
  },
  {
    title: 'Movies with Meryl Streep',
    slug: 'movies-with-meryl-streep',
    type: 'actor',
    description: 'Movies starring Meryl Streep.',
    rules: { actor: 'Meryl Streep' },
    sort: 'rating',
    limit: 40,
  },
  {
    title: 'Movies with Christian Bale',
    slug: 'movies-with-christian-bale',
    type: 'actor',
    description: 'Movies starring Christian Bale.',
    rules: { actor: 'Christian Bale' },
    sort: 'rating',
    limit: 40,
  },
  {
    title: 'Movies with Keanu Reeves',
    slug: 'movies-with-keanu-reeves',
    type: 'actor',
    description: 'Movies starring Keanu Reeves.',
    rules: { actor: 'Keanu Reeves' },
    sort: 'rating',
    limit: 40,
  },
  {
    title: 'Movies with Emma Stone',
    slug: 'movies-with-emma-stone',
    type: 'actor',
    description: 'Movies starring Emma Stone.',
    rules: { actor: 'Emma Stone' },
    sort: 'rating',
    limit: 40,
  },
  {
    title: 'Movies with Ryan Gosling',
    slug: 'movies-with-ryan-gosling',
    type: 'actor',
    description: 'Movies starring Ryan Gosling.',
    rules: { actor: 'Ryan Gosling' },
    sort: 'rating',
    limit: 40,
  },

  // ── Genres ────────────────────────────────────────────────────────────────────
  {
    title: 'Best Science Fiction Movies',
    slug: 'best-science-fiction-movies',
    type: 'genre',
    description: 'Highly rated science fiction movies.',
    rules: { genre: 'Science Fiction' },
    sort: 'rating',
    limit: 100,
  },
  {
    title: 'Best Horror Movies',
    slug: 'best-horror-movies',
    type: 'genre',
    description: 'Highly rated horror movies.',
    rules: { genre: 'Horror' },
    sort: 'rating',
    limit: 100,
  },
  {
    title: 'Best Romance Movies',
    slug: 'best-romance-movies',
    type: 'genre',
    description: 'Highly rated romance movies.',
    rules: { genre: 'Romance' },
    sort: 'rating',
    limit: 100,
  },
  {
    title: 'Best Action Movies',
    slug: 'best-action-movies',
    type: 'genre',
    description: 'Highly rated action movies.',
    rules: { genre: 'Action' },
    sort: 'rating',
    limit: 100,
  },
  {
    title: 'Best Comedy Movies',
    slug: 'best-comedy-movies',
    type: 'genre',
    description: 'Highly rated comedy movies.',
    rules: { genre: 'Comedy' },
    sort: 'rating',
    limit: 100,
  },
  {
    title: 'Best Adventure Movies',
    slug: 'best-adventure-movies',
    type: 'genre',
    description: 'Highly rated adventure movies.',
    rules: { genre: 'Adventure' },
    sort: 'rating',
    limit: 100,
  },
  {
    title: 'Best War Movies',
    slug: 'best-war-movies',
    type: 'genre',
    description: 'Highly rated war movies.',
    rules: { genre: 'War' },
    sort: 'rating',
    limit: 100,
  },
  {
    title: 'Best Western Movies',
    slug: 'best-western-movies',
    type: 'genre',
    description: 'Highly rated western movies.',
    rules: { genre: 'Western' },
    sort: 'rating',
    limit: 100,
  },
  {
    title: 'Best Documentary Movies',
    slug: 'best-documentary-movies',
    type: 'genre',
    description: 'Highly rated documentary movies.',
    rules: { genre: 'Documentary' },
    sort: 'rating',
    limit: 100,
  },
  {
    title: 'Best Animation Movies',
    slug: 'best-animation-movies',
    type: 'genre',
    description: 'Highly rated animation movies.',
    rules: { genre: 'Animation' },
    sort: 'rating',
    limit: 100,
  },

  // ── TV Shows ──────────────────────────────────────────────────────────────────
  {
    title: 'Best Sitcoms Ever',
    slug: 'best-sitcoms-ever',
    type: 'tv',
    description: 'The greatest sitcoms of all time.',
    rules: { media_type: 'tv', tv_genre_id: 35 },
    sort: 'rating',
    limit: 80,
  },
  {
    title: 'Best HBO Shows',
    slug: 'best-hbo-shows',
    type: 'tv',
    description: 'Premium drama and genre television from HBO.',
    rules: { media_type: 'tv', network_id: 49 },
    sort: 'rating',
    limit: 80,
  },
  {
    title: 'Best Netflix Originals',
    slug: 'best-netflix-originals',
    type: 'tv',
    description: 'Original series produced by Netflix.',
    rules: { media_type: 'tv', network_id: 213 },
    sort: 'rating',
    limit: 80,
  },
  {
    title: 'Best Mini Series',
    slug: 'best-mini-series',
    type: 'tv',
    description: 'Compelling limited series with complete stories.',
    // with_type 2 = Miniseries on TMDB
    rules: { media_type: 'tv', with_type: 2 },
    sort: 'rating',
    limit: 80,
  },
  {
    title: 'Best Crime TV Shows',
    slug: 'best-crime-tv-shows',
    type: 'tv',
    description: 'Gripping crime dramas and thrillers.',
    rules: { media_type: 'tv', tv_genre_id: 80 },
    sort: 'rating',
    limit: 80,
  },
  {
    title: 'Best Sci‑Fi TV Shows',
    slug: 'best-scifi-tv-shows',
    type: 'tv',
    description: 'The best science fiction and fantasy on television.',
    rules: { media_type: 'tv', tv_genre_id: 10765 },
    sort: 'rating',
    limit: 80,
  },
  {
    title: 'Best Fantasy TV Shows',
    slug: 'best-fantasy-tv-shows',
    type: 'tv',
    description: 'Epic fantasy worlds brought to life on screen.',
    rules: { media_type: 'tv', tv_genre_id: 10765 },
    sort: 'rating',
    limit: 80,
  },
  {
    title: 'Best Animated TV Shows',
    slug: 'best-animated-tv-shows',
    type: 'tv',
    description: 'Top-rated animated series for all ages.',
    rules: { media_type: 'tv', tv_genre_id: 16 },
    sort: 'rating',
    limit: 80,
  },
  {
    title: 'Best Mystery Shows',
    slug: 'best-mystery-shows',
    type: 'tv',
    description: 'Suspenseful mystery and detective shows.',
    rules: { media_type: 'tv', tv_genre_id: 9648 },
    sort: 'rating',
    limit: 80,
  },
  {
    title: 'Best Teen TV Shows',
    slug: 'best-teen-tv-shows',
    type: 'tv',
    description: 'Coming-of-age stories and youth drama.',
    rules: { media_type: 'tv', tv_genre_id: 10762 },
    sort: 'rating',
    limit: 80,
  },

  // ── Decades ───────────────────────────────────────────────────────────────────
  {
    title: 'Best Movies of the 1960s',
    slug: 'best-movies-of-the-1960s',
    type: 'decade',
    description: 'Top movies released in the 1960s.',
    rules: { release_date_gte: 1960, release_date_lte: 1969 },
    sort: 'rating',
    limit: 100,
  },
  {
    title: 'Best Movies of the 1970s',
    slug: 'best-movies-of-the-1970s',
    type: 'decade',
    description: 'Top movies released in the 1970s.',
    rules: { release_date_gte: 1970, release_date_lte: 1979 },
    sort: 'rating',
    limit: 100,
  },
  {
    title: 'Best Movies of the 1980s',
    slug: 'best-movies-of-the-1980s',
    type: 'decade',
    description: 'Top movies released in the 1980s.',
    rules: { release_date_gte: 1980, release_date_lte: 1989 },
    sort: 'rating',
    limit: 100,
  },
  {
    title: 'Best Movies of the 1990s',
    slug: 'best-movies-of-the-1990s',
    type: 'decade',
    description: 'Top movies released in the 1990s.',
    rules: { release_date_gte: 1990, release_date_lte: 1999 },
    sort: 'rating',
    limit: 100,
  },
  {
    title: 'Best Movies of the 2000s',
    slug: 'best-movies-of-the-2000s',
    type: 'decade',
    description: 'Top movies released in the 2000s.',
    rules: { release_date_gte: 2000, release_date_lte: 2009 },
    sort: 'rating',
    limit: 100,
  },
  {
    title: 'Best Movies of the 2010s',
    slug: 'best-movies-of-the-2010s',
    type: 'decade',
    description: 'Top movies released in the 2010s.',
    rules: { release_date_gte: 2010, release_date_lte: 2019 },
    sort: 'rating',
    limit: 100,
  },
  {
    title: 'Best Movies of the 2020s',
    slug: 'best-movies-of-the-2020s',
    type: 'decade',
    description: 'Top movies released in the 2020s.',
    rules: { release_date_gte: 2020, release_date_lte: 2029 },
    sort: 'rating',
    limit: 100,
  },

  // ── Mood ──────────────────────────────────────────────────────────────────────
  {
    title: 'Perfect Date Night Movies',
    slug: 'perfect-date-night-movies',
    type: 'mood',
    description: 'Romantic picks for a perfect evening in.',
    rules: { genres: ['Romance', 'Comedy'] },
    sort: 'rating',
    limit: 60,
  },
  {
    title: 'Girls Night Movies',
    slug: 'girls-night-movies',
    type: 'mood',
    description: 'Fun, fierce, and fabulous films for a girls night.',
    rules: { genres: ['Comedy', 'Romance', 'Drama'] },
    sort: 'rating',
    limit: 60,
  },
  {
    title: 'Movies to Watch with Friends',
    slug: 'movies-to-watch-with-friends',
    type: 'mood',
    description: 'Crowd-pleasing movies everyone will enjoy.',
    rules: { genres: ['Comedy', 'Action', 'Adventure'] },
    sort: 'rating',
    limit: 60,
  },
  {
    title: 'Movies That Will Make You Cry',
    slug: 'movies-that-will-make-you-cry',
    type: 'mood',
    description: 'Emotional films that will move you deeply.',
    rules: { genres: ['Drama', 'Romance'] },
    sort: 'rating',
    limit: 60,
  },
  {
    title: 'Feel‑Good Movies',
    slug: 'feelgood-movies',
    type: 'mood',
    description: 'Uplifting films guaranteed to brighten your day.',
    rules: { genres: ['Comedy', 'Animation', 'Family'] },
    sort: 'rating',
    limit: 60,
  },
  {
    title: 'Cozy Sunday Movies',
    slug: 'cozy-sunday-movies',
    type: 'mood',
    description: 'Warm, easy-going films for a lazy weekend.',
    rules: { genres: ['Comedy', 'Drama', 'Family'] },
    sort: 'rating',
    limit: 60,
  },
  {
    title: 'Rainy Day Movies',
    slug: 'rainy-day-movies',
    type: 'mood',
    description: 'Absorbing films perfect for a grey, quiet day.',
    rules: { genres: ['Drama', 'Thriller', 'Mystery'] },
    sort: 'rating',
    limit: 60,
  },
  {
    title: 'Late Night Movies',
    slug: 'late-night-movies',
    type: 'mood',
    description: 'Gripping, atmospheric films for after dark.',
    rules: { genres: ['Horror', 'Thriller', 'Mystery'] },
    sort: 'rating',
    limit: 60,
  },
  {
    title: 'Mind‑Bending Movies',
    slug: 'mindbending-movies',
    type: 'mood',
    description: 'Films that twist your perception of reality.',
    rules: { genres: ['Science Fiction', 'Thriller'] },
    sort: 'rating',
    limit: 60,
  },
  {
    title: 'Comfort Movies',
    slug: 'comfort-movies',
    type: 'mood',
    description: 'Safe, familiar films that feel like a warm hug.',
    rules: { genres: ['Comedy', 'Family', 'Animation'] },
    sort: 'rating',
    limit: 60,
  },

  // ── Awards ────────────────────────────────────────────────────────────────────
  {
    title: 'Oscar Best Picture Winners',
    slug: 'oscar-best-picture-winners',
    type: 'awards',
    description: 'Academy Award Best Picture winners.',
    rules: { keywords: ['academy award for best picture'] },
    sort: 'rating',
    limit: 100,
  },
  {
    title: 'Oscar Best Animated Feature Winners',
    slug: 'oscar-best-animated-feature-winners',
    type: 'awards',
    description: 'Academy Award Best Animated Feature winners.',
    rules: { keywords: ['academy award for best animated feature film'] },
    sort: 'rating',
    limit: 100,
  },
  {
    title: "Cannes Palme d'Or Winners",
    slug: 'cannes-palme-dor-winners',
    type: 'awards',
    description: "Films that won the Palme d'Or at Cannes.",
    rules: { keywords: ["palme d'or"] },
    sort: 'rating',
    limit: 100,
  },
  {
    title: 'Golden Globe Best Drama Winners',
    slug: 'golden-globe-best-drama-winners',
    type: 'awards',
    description: 'Golden Globe Award Best Drama Film winners.',
    rules: { keywords: ['golden globe award for best motion picture drama'] },
    sort: 'rating',
    limit: 100,
  },
  {
    title: 'BAFTA Best Film Winners',
    slug: 'bafta-best-film-winners',
    type: 'awards',
    description: 'BAFTA Award for Best Film winners.',
    rules: { keywords: ['bafta award for best film'] },
    sort: 'rating',
    limit: 100,
  },

  // ── Themes ────────────────────────────────────────────────────────────────────
  {
    title: 'Best Time Travel Movies',
    slug: 'best-time-travel-movies',
    type: 'theme',
    description: 'Movies centered around time travel.',
    rules: { keywords: ['time travel'] },
    sort: 'rating',
    limit: 80,
  },
  {
    title: 'Best Space Movies',
    slug: 'best-space-movies',
    type: 'theme',
    description: 'Epic adventures set in the cosmos.',
    rules: { keywords: ['space', 'outer space'] },
    sort: 'rating',
    limit: 80,
  },
  {
    title: 'Best AI Movies',
    slug: 'best-ai-movies',
    type: 'theme',
    description: 'Films exploring artificial intelligence.',
    rules: { keywords: ['artificial intelligence', 'robot'] },
    sort: 'rating',
    limit: 80,
  },
  {
    title: 'Best Hacker Movies',
    slug: 'best-hacker-movies',
    type: 'theme',
    description: 'Cyber-thriller films about hackers and tech.',
    rules: { keywords: ['hacker', 'computer hacker'] },
    sort: 'rating',
    limit: 80,
  },
  {
    title: 'Best Heist Movies',
    slug: 'best-heist-movies',
    type: 'theme',
    description: 'Slick, clever heist films.',
    rules: { keywords: ['heist', 'robbery'] },
    sort: 'rating',
    limit: 80,
  },
  {
    title: 'Best Zombie Movies',
    slug: 'best-zombie-movies',
    type: 'theme',
    description: 'The undead rise in these horror films.',
    rules: { keywords: ['zombie', 'undead'] },
    sort: 'rating',
    limit: 80,
  },
  {
    title: 'Best Vampire Movies',
    slug: 'best-vampire-movies',
    type: 'theme',
    description: 'Films featuring the iconic vampire mythos.',
    rules: { keywords: ['vampire'] },
    sort: 'rating',
    limit: 80,
  },
  {
    title: 'Best Dystopian Movies',
    slug: 'best-dystopian-movies',
    type: 'theme',
    description: 'Dark visions of a bleak future.',
    rules: { keywords: ['dystopia', 'post-apocalypse'] },
    sort: 'rating',
    limit: 80,
  },
  {
    title: 'Best Cyberpunk Movies',
    slug: 'best-cyberpunk-movies',
    type: 'theme',
    description: 'High-tech, low-life cyberpunk cinema.',
    rules: { keywords: ['cyberpunk'] },
    sort: 'rating',
    limit: 80,
  },
  {
    title: 'Best Movies Based on True Stories',
    slug: 'best-movies-based-on-true-stories',
    type: 'theme',
    description: 'Compelling films inspired by real events.',
    rules: { keywords: ['based on a true story', 'based on true events'] },
    sort: 'rating',
    limit: 80,
  },

  // ── Classics ──────────────────────────────────────────────────────────────────
  {
    title: 'Cult Classic Movies',
    slug: 'cult-classic-movies',
    type: 'classics',
    description: 'Films with devoted cult followings.',
    rules: { keywords: ['cult film'] },
    sort: 'rating',
    limit: 120,
  },
  {
    title: 'Must‑Watch Movie Classics',
    slug: 'mustwatch-movie-classics',
    type: 'classics',
    description: 'Essential films every cinephile should see.',
    rules: { rating_gte: 7.5 },
    sort: 'rating',
    limit: 120,
  },
  {
    title: 'Movies Everyone Should See Once',
    slug: 'movies-everyone-should-see-once',
    type: 'classics',
    description: 'Culturally defining films that shaped cinema.',
    rules: { rating_gte: 7.5 },
    sort: 'rating',
    limit: 120,
  },
];

/** Number of collections available to free (signed-in) users. The rest require Pro. */
export const FREE_COLLECTIONS_LIMIT = 5;

export function getCollectionBySlug(slug: string): Collection | undefined {
  return COLLECTIONS.find(c => c.slug === slug);
}

/** Collections grouped by type for browse UI */
export function getCollectionsByType(): Record<CollectionType, Collection[]> {
  return COLLECTIONS.reduce((acc, c) => {
    if (!acc[c.type]) acc[c.type] = [];
    acc[c.type].push(c);
    return acc;
  }, {} as Record<CollectionType, Collection[]>);
}
