/**
 * Central config reader.
 * Priority: runtime injection (window.__ENV__) > build-time Vite env vars > empty string.
 *
 * Production: window.__ENV__ is generated by docker-entrypoint.sh from container env vars.
 * Community:  same mechanism, users set vars in docker-compose.
 * Dev:        use VITE_* vars in .env.local, or leave empty for BYO-key mode.
 */
const env = typeof window !== 'undefined' ? ((window as any).__ENV__ ?? {}) : {};

export const config = {
  /**
   * If set, all AI recommendation calls are routed through this proxy (production managed AI).
   * The proxy holds the real API key server-side and enforces rate limits.
   * If empty, the frontend calls AI providers directly with the user's BYO key (community/dev).
   */
  aiProxyUrl: env.AI_PROXY_URL || import.meta.env.VITE_AI_PROXY_URL || '',

  /** Monthly AI recommendation limit for free users via the proxy. */
  aiFreeMonthlyLimit: Number(env.AI_FREE_MONTHLY_LIMIT || import.meta.env.VITE_AI_FREE_MONTHLY_LIMIT || 30),

  /** Daily AI recommendation limit for Pro users via the proxy. */
  aiProDailyLimit: Number(env.AI_PRO_DAILY_LIMIT || import.meta.env.VITE_AI_PRO_DAILY_LIMIT || 50),

  /** Supabase — used for auth + cross-device sync (Phase 2). */
  supabaseUrl: env.SUPABASE_URL || import.meta.env.VITE_SUPABASE_URL || '',
  supabaseAnonKey: env.SUPABASE_ANON_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY || '',

  get hasManagedAI(): boolean { return !!this.aiProxyUrl; },
  get hasSync(): boolean { return !!(this.supabaseUrl && this.supabaseAnonKey); },
};
